# -*- coding: utf-8 -*-
"""For_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vIDh_MXT_St7xU3LTR_W80hjOrNvZAek
"""

for i in range(0,10,2):
  print(i)

#simple interest calculation
p=int(input("Enter principal"))
r=int(input('rate of interest'))
t=int(input('number of years'))
interest=0

for i in range(0,t):
  interest=(p*r)/100
  p=p+interest #Amount at the time of withdrawl
print(p)

#sum of all numbers in a given range
low_range=int(input("enter the lower range"))
up_range=int(input("enter the upper range"))

sum=0
i=0
for i in range(low_range, up_range):
  sum+=i

print(sum)

fruits=['Apple','PineApple','Mango','Cherry','Elderberry']

for fruit in fruits:
  print(fruit, end=" ")

l1=[1,2,3,4,5]

for i in l1:
  print(i, end=" ")

for i in range(10): #[0,1,2,3,4,5,6,7,8,9]
  print(i)

for i in range(1,11): #step=1 bydefault
  print(i,end=" ")

for i in range(1,11,2): #every 2nd element gets skipped
  print(i)

for i in range(2,10,3):
  print(i)

for i in range(11,1,-1):
  print(i)

l1=[1,2,3,4,5]

for i in l1:
  if i==3:
    continue
  print(i)

l1=[1,2,3,4,5]

for i in l1:
  if i==3:
    break
  print(i)